### ISSUE TITLE
Accept different host?

### ISSUE THREAD

**Issue by EugeneKallis** [jshinonome/geek#1]
Hey, someone just pointed me to your package, i see its new and being actively developed on. Is there plans to add a Host to the QProcess?

**Comment by jshinonome** [comment]
Hi, Yes, it is still in development. I took the host off QProcess so that you have to run qEngine on the same box with q processes. Same box means no compressed IPC messages. If you are interested in this package, shall we have a session about this package?

**Comment by EugeneKallis** [comment]
Ill he honest, i started learning GoLang about 2 weeks ago. At work we use KDB which im also relatively new with. Someone on the KX forum recommended your package since i was requesting something up to date. Currently i was looking at github.com/sv/kdbgo. 

Im just trying to do some prototypes so i can possibly introduce my company to Golang. It would be cool to be able to connect to multiple hosts because i know at work we run some services and connect to a DB running on difference boxes. I look forward to watching this grow. I really want to make use of the q.Sync. The other package i have to loop through row by row assigning the index to a struct.

**Comment by jshinonome** [comment]
It is not difficult to make it support other hosts. I removed this to reduce latency. I want to know more about your use cases, so I can adjust my package accordingly. How about setuping a call with you?

**Comment by EugeneKallis** [comment]
I do appreciate your willingness to help but Im sorry Im not comfortable with a phone call. I can type my needs out here, Im writing a Rest API. The db is just where i store data so ill be connecting to KDB to pull tables and serve to my front end. I will also be making updates to tables from frontend. Main calls will be like "select from table where .." or "`table upsert ()"

**Comment by jshinonome** [comment]
Understood. I will try to add back the host field this weekend.

**Comment by EugeneKallis** [comment]
Thank you so much, i really appreciate. Also very nice work on the Q extension for VSCode. Made my life so much easier

**Comment by jshinonome** [comment]
I have added the host field to qProcess in v0.1.0, give it a try, and let me know if it works.

**Comment by EugeneKallis** [comment]
Hey @jshinonome  Looks good, one question, how would i just query for a table? If i go by the example it needs a Api/Sym struct? But how can i just get table. heres what i came up with.
 `func main() {
	q := geek.QProcess{Host: "192.168.1.91", Port: 5001}
	q.Dial()
	r := make([]Linkgroup, 100)
	f := struct {
		Api string
		Sym string
	}{"getTable", "`linkgroups"}
	err := q.Sync(&r, f)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r)
	for _, t := range r {
		fmt.Printf("%+v\n", t)
	}

}

type Linkgroup struct {
	ID          string    `k:"id"`
	Dispname    string    `k:"dispname"`
	Order       int32     `k:"order"`
	Update_Time time.Time `k:"update_time"`
}
`

**Comment by jshinonome** [comment]
Struct without k tags is a mixed list, this is a way of calling defined API on the q process. if you want to send pure script, use `[]bytes("select from table where ...")`

**Comment by EugeneKallis** [comment]
Like below? For some reason its not returning anything

```
func main() {
	q := geek.QProcess{Host: "192.168.1.91", Port: 5001}
	q.Dial()
	r := make([]Linkgroup, 0)
	err := q.Sync(&r, []byte("0!select from linkgroups"))
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r)

}

type Linkgroup struct {
	ID          string    `k:"id"`
	Dispname    string    `k:"dispname"`
	Order       int32     `k:"order"`
	Update_Time time.Time `k:"update_time"`
}
```

**Comment by jshinonome** [comment]
Yes, no error message?

**Comment by EugeneKallis** [comment]
No, console just prints empty []

**Comment by jshinonome** [comment]
Oh, geek doesn't support int32 at the moment, so it should throw an error.

**Comment by EugeneKallis** [comment]
So i updated to a table that doesnt use int. 

```
func main() {
	q := geek.QProcess{Host: "192.168.1.91", Port: 5001}
	q.Dial()
	r := make([]User, 0)
	err := q.Sync(&r, []byte("0!select from users"))
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r)

}

type User struct {
	User     string `k:"user"`
	Password string `k:"password"`
}
```
Table meta
```
c       | t f a
--------| -----
user    | s    
password| C    
```
Output
```
$ go run .
[]
```

**Comment by jshinonome** [comment]
You have to use []byte for password. 
q symbol -> string
q string -> []byte
I will add int32 and float32.

**Comment by jshinonome** [comment]
A bit weird, if I put the wrong type, my console shows me
`geek:readK nyi target type:[]int32, k type:7`

**Comment by jshinonome** [comment]
Looks like there is a bug with host that doesn't show error message, I will take a look.

**Comment by EugeneKallis** [comment]
I wonder what im doing wrong because i changed my Password to a []byte and same result, empty array. I will help debug as needed

**Comment by jshinonome** [comment]
Sorry, I just push v0.1.1, the error was shadowed...

**Comment by EugeneKallis** [comment]
Ok i updated, same result.

Sidenote, i ran my DB locally to try doing the select from users to my struct. i see the below. Which is weird becauese i dont have an int in this table.

```
$ go run main.go 
geek:readK nyi target type:[][]uint8, k type:0
[]
```

**Comment by jshinonome** [comment]
Great, it shows error now. [][]uint8 is actually [][]byte.
Let me take a look.

**Comment by EugeneKallis** [comment]
Well i took the host out and got that error. With host in there the error still doesnt show

**Comment by jshinonome** [comment]
Could you try v0.1.2?
- If []byte works
- Can show error with host

**Comment by EugeneKallis** [comment]
[]byte works now and it also works with host!

Thank you

**Comment by jshinonome** [comment]
You are welcome :)
